/*
 * Generated by scripts/gen_display_art.py — edit that script, not this file.
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include <lvgl.h>

#define FIRE_FRAME_COUNT 16
#define FIRE_FRAME_W 64  /* framebuffer-space: pre-rotated 90 deg */
#define FIRE_FRAME_H 32

extern const lv_img_dsc_t *fire_frames[FIRE_FRAME_COUNT];
extern const lv_img_dsc_t mug_art;
